"""Test v1.1 generators."""


import pytest

from forgemind.core.analysis import analyze_project
from forgemind.generators import (
    generate_ai_risk_checklist,
    generate_context,
    generate_issue_template,
    generate_pr_template,
    generate_tool_permission_matrix,
)


@pytest.fixture
def sample_ai_project_file(tmp_path):
    """Create a sample AI project file."""
    project_content = """# AI Agent Project

## Objective
Develop an AI agent to automate backend service generation.

## Context
Team spends 4-6 hours per service on boilerplate setup.

## Scope
- Read service specifications
- Generate boilerplate code
- Validate against patterns
- Submit PR for review

## Out of Scope
- Database schema design
- Production deployment

## Constraints
- No external API calls
- Must work offline
- Audit trail required

## Stakeholders
- Engineering Lead: PR approver
- Security Team: code reviewer

## Current State
Manual backend setup takes 4-6 hours per service.

## Desired State
Agent generates 80% of boilerplate in <30 minutes.

## Risks
- Agent generates insecure code
- Agent hallucinates patterns
- Scope creeps to dangerous operations

## Success Criteria
- Generated code passes linter and tests
- Security review completes in <1 hour
- First 5 agents ship successfully
"""
    project_file = tmp_path / "ai_project.md"
    project_file.write_text(project_content)
    return str(project_file)


@pytest.fixture
def sample_analysis(sample_ai_project_file):
    """Analyze sample AI project."""
    return analyze_project(sample_ai_project_file)


def test_context_generator_produces_markdown(sample_analysis):
    """Test context generator produces valid markdown."""
    context = generate_context(sample_analysis)
    assert isinstance(context, str)
    assert "Generated by ForgeMind" in context
    assert "Agent Instruction Context" in context
    assert "Objective" in context
    assert "Acceptance Criteria" in context
    assert "Rollback Plan" in context


def test_context_generator_includes_risks(sample_analysis):
    """Test context includes top risks."""
    context = generate_context(sample_analysis)
    assert "Top Risks & Mitigation" in context
    # Should have at least one risk
    assert "⚠" in context or "Risk" in context


def test_context_generator_includes_assumptions(sample_analysis):
    """Test context includes key assumptions."""
    context = generate_context(sample_analysis)
    assert "Key Assumptions to Validate" in context


def test_ai_risk_checklist_produces_markdown(sample_analysis):
    """Test AI risk checklist produces valid markdown."""
    checklist = generate_ai_risk_checklist(sample_analysis)
    assert isinstance(checklist, str)
    assert "Generated by ForgeMind" in checklist
    assert "AI Risk Readiness Checklist" in checklist
    assert "Progress:" in checklist


def test_ai_risk_checklist_has_items(sample_analysis):
    """Test AI risk checklist includes items."""
    checklist = generate_ai_risk_checklist(sample_analysis)
    assert "Checklist" in checklist
    # Should have checkmark or warning indicators
    assert "✅" in checklist or "⚠️" in checklist


def test_ai_risk_checklist_domain_specific(sample_analysis):
    """Test AI risk checklist is domain-specific."""
    checklist = generate_ai_risk_checklist(sample_analysis)
    # Should have domain-specific content with checklist items
    checklist_lower = checklist.lower()
    assert "checklist" in checklist_lower
    # Should have items evaluated (indicated by check/warning marks)
    assert ("✅" in checklist or "⚠️" in checklist or "- [ ]" in checklist)


def test_tool_permission_matrix_produces_markdown(sample_analysis):
    """Test tool permission matrix produces valid markdown."""
    matrix = generate_tool_permission_matrix(sample_analysis)
    assert isinstance(matrix, str)
    assert "Generated by ForgeMind" in matrix
    assert "Tool Permission Matrix" in matrix
    assert "|" in matrix  # Should be a table


def test_tool_permission_matrix_has_tools(sample_analysis):
    """Test tool permission matrix includes tools."""
    matrix = generate_tool_permission_matrix(sample_analysis)
    # Should have tool rows
    assert "Allowed" in matrix or "Denied" in matrix or "Restricted" in matrix


def test_tool_permission_matrix_shows_permissions(sample_analysis):
    """Test tool permission matrix shows permission status."""
    matrix = generate_tool_permission_matrix(sample_analysis)
    # Should have permission indicators
    assert "✅" in matrix or "❌" in matrix or "⚠️" in matrix


def test_pr_template_produces_markdown(sample_analysis):
    """Test PR template produces valid markdown."""
    template = generate_pr_template(sample_analysis)
    assert isinstance(template, str)
    assert "Generated by ForgeMind" in template
    assert "Description" in template or "description" in template.lower()


def test_pr_template_has_checklist(sample_analysis):
    """Test PR template includes checklist."""
    template = generate_pr_template(sample_analysis)
    assert "[ ]" in template  # Checkbox syntax
    assert "Code passes linter" in template or "linter" in template.lower()


def test_pr_template_has_approval_gates(sample_analysis):
    """Test PR template includes approval gates."""
    template = generate_pr_template(sample_analysis)
    assert "Approval" in template or "approval" in template.lower()
    assert "Merge" in template or "merge" in template.lower()


def test_issue_template_produces_markdown(sample_analysis):
    """Test issue template produces valid markdown."""
    template = generate_issue_template(sample_analysis)
    assert isinstance(template, str)
    assert "Generated by ForgeMind" in template
    assert "Issue Type" in template or "issue" in template.lower()


def test_issue_template_has_sections(sample_analysis):
    """Test issue template has standard sections."""
    template = generate_issue_template(sample_analysis)
    assert "Description" in template
    assert "Environment" in template or "environment" in template.lower()


def test_issue_template_has_checkboxes(sample_analysis):
    """Test issue template uses checkboxes."""
    template = generate_issue_template(sample_analysis)
    assert "[ ]" in template  # Checkbox syntax


def test_all_generators_handle_minimal_project(tmp_path):
    """Test generators handle projects with minimal input."""
    minimal_project = tmp_path / "minimal.md"
    minimal_project.write_text("# Minimal Project\n\n## Objective\nDo something")
    analysis = analyze_project(str(minimal_project))

    # All generators should produce output without errors
    context = generate_context(analysis)
    assert isinstance(context, str)

    checklist = generate_ai_risk_checklist(analysis)
    assert isinstance(checklist, str)

    matrix = generate_tool_permission_matrix(analysis)
    assert isinstance(matrix, str)

    pr_template = generate_pr_template(analysis)
    assert isinstance(pr_template, str)

    issue_template = generate_issue_template(analysis)
    assert isinstance(issue_template, str)
