"""Markdown export with Jinja2 templates."""

from pathlib import Path

from forgemind.schemas.project import ProjectAnalysis


def export_markdown(analysis: ProjectAnalysis, output_dir: Path) -> Path:
    """Export analysis to Markdown files."""
    output_dir.mkdir(parents=True, exist_ok=True)

    # Helper to add header to markdown files
    def add_header(content: str) -> str:
        header = "Generated by ForgeMind\nThis output is a readiness aid, not a certification or compliance guarantee.\n\n"
        return header + content

    # 1. PROJECT_CHARTER.md
    charter = f"""# {analysis.metadata.name} - Project Charter

## Project Identification
- **Project Name:** {analysis.metadata.name}
- **Domain:** {analysis.metadata.domain}
- **Maturity:** {analysis.maturity_estimate}

## Objective
{analysis.input.objective}

## Business Context
{analysis.input.context}

## Scope
{analysis.input.scope}

## Out of Scope
{analysis.input.out_of_scope or "Not specified"}

## Constraints
{analysis.input.constraints}

## Success Criteria
{analysis.input.success_criteria or "Not specified"}

## Stakeholders
{analysis.input.stakeholders or "Not specified"}
"""
    (output_dir / "PROJECT_CHARTER.md").write_text(add_header(charter))

    # 2. RDMAICSI_MATRIX.md
    rdmaicsi = "# RDMAICSI Matrix\n\nEight-phase continuous improvement framework\n\n"
    for phase in analysis.rdmaicsi_phases:
        rdmaicsi += f"""## {phase['phase']}

**Purpose:** {phase['purpose']}

**Key Questions:**
{chr(10).join(f"- {q}" for q in phase['key_questions'])}

**Required Evidence:**
{chr(10).join(f"- {e}" for e in phase['required_evidence'])}

**Expected Output:** {phase['expected_output']}

**Risk if Skipped:** {phase['risk_if_skipped']}

---
"""
    (output_dir / "RDMAICSI_MATRIX.md").write_text(add_header(rdmaicsi))

    # 3. SENGE_LENS.md
    senge = "# Senge's Five Disciplines\n\nLearning organization perspective\n\n"
    for disc in analysis.senge_disciplines:
        senge += f"""## {disc['discipline']}

**Purpose:** {disc['purpose']}

**Diagnostic Questions:**
{chr(10).join(f"- {q}" for q in disc['diagnostic_questions'])}

**Project Risk if Ignored:** {disc['project_risk_if_ignored']}

**Recommended Practice:** {disc['recommended_practice']}

---
"""
    (output_dir / "SENGE_LENS.md").write_text(add_header(senge))

    # 4. LEAN_WASTE_SCAN.md
    lean = "# Lean Waste Scan\n\nIdentifying flow inefficiencies\n\n"
    lean += "## Waste Categories\n\n"
    for waste_type, findings in analysis.lean_findings.get("waste_scan", {}).items():
        lean += f"### {waste_type.replace('_', ' ').title()}\n"
        for finding in findings:
            lean += f"- {finding}\n"
        lean += "\n"

    lean += "## Flow Risks\n"
    for risk in analysis.lean_findings.get("flow_risks", []):
        lean += f"- {risk}\n"

    lean += "\n## Standard Work Opportunities\n"
    for opp in analysis.lean_findings.get("standard_work_opportunities", []):
        lean += f"- {opp}\n"

    lean += "\n## Rework Risks\n"
    for risk in analysis.lean_findings.get("rework_risks", []):
        lean += f"- {risk}\n"

    lean += "\n## Handoff Risks\n"
    for risk in analysis.lean_findings.get("handoff_risks", []):
        lean += f"- {risk}\n"

    (output_dir / "LEAN_WASTE_SCAN.md").write_text(add_header(lean))

    # 5. RISK_REGISTER.md
    risk_reg = "# Risk Register\n\n"
    for risk in analysis.risks:
        risk_reg += f"""## {risk['id']}: {risk['risk']}

- **Cause:** {risk['cause']}
- **Impact:** {risk['impact']}
- **Probability:** {risk['probability']}
- **Severity:** {risk['severity']}
- **Mitigation:** {risk['mitigation']}
- **Owner:** {risk['owner_placeholder']}
- **Requires Human Review:** {'Yes' if risk['human_review_required'] else 'No'}

---
"""
    (output_dir / "RISK_REGISTER.md").write_text(add_header(risk_reg))

    # 6. ASSUMPTION_LOG.md
    assumptions = "# Assumption Log\n\n"
    for assumption in analysis.assumptions:
        assumptions += f"""## Assumption
{assumption['assumption']}

- **Source:** {assumption['source']}
- **Risk if False:** {assumption['risk_if_false']}
- **Validation Needed:** {'Yes' if assumption['validation_needed'] else 'No'}
- **Status:** {assumption['status']}

---
"""
    (output_dir / "ASSUMPTION_LOG.md").write_text(add_header(assumptions))

    # 7. ACCEPTANCE_CRITERIA.md
    criteria = "# Acceptance Criteria\n\n"
    for criterion in analysis.acceptance_criteria:
        criteria += f"""## {criterion['id']}: {criterion['criterion']}

- **Verification Method:** {criterion['verification_method']}
- **Evidence Expected:** {criterion['evidence_expected']}
- **Owner:** {criterion['owner_placeholder']}

---
"""
    (output_dir / "ACCEPTANCE_CRITERIA.md").write_text(add_header(criteria))

    # 8. BACKLOG.md
    backlog = "# Prioritized Backlog\n\n"
    for priority in ["P0", "P1", "P2", "P3"]:
        priority_items = [i for i in analysis.backlog if i['priority'] == priority]
        if priority_items:
            backlog += f"## {priority} - {['Critical', 'Important', 'Useful', 'Polish'][['P0', 'P1', 'P2', 'P3'].index(priority)]}\n\n"
            for item in priority_items:
                backlog += f"""### {item['id']}: {item['task']}

- **Epic:** {item['epic']}
- **Impact:** {item['impact']}
- **Effort:** {item['effort']}
- **Dependency:** {item['dependency'] or 'None'}
- **Acceptance Criteria:** {', '.join(item.get('acceptance_criteria', [])) if item.get('acceptance_criteria') else 'TBD'}

---
"""
    (output_dir / "BACKLOG.md").write_text(add_header(backlog))

    # 9. CONTROL_PLAN.md
    control = "# Control Plan\n\n"
    for item in analysis.control_plan:
        control += f"""## {item['control_item']}

- **Method:** {item['method']}
- **Frequency:** {item['frequency']}
- **Owner:** {item['owner_placeholder']}
- **Evidence:** {item['evidence']}
- **Reaction if Failed:** {item['reaction_plan_if_failed']}

---
"""
    (output_dir / "CONTROL_PLAN.md").write_text(add_header(control))

    # 10. DECISION_LOG.md
    decisions = "# Decision Log\n\n"
    for decision in analysis.decision_log:
        decisions += f"""## {decision['id']}: {decision['decision']}

- **Context:** {decision['context']}
- **Alternatives Considered:** {', '.join(decision['alternatives_considered']) if decision['alternatives_considered'] else 'TBD'}
- **Rationale:** {decision['rationale']}
- **Owner:** {decision['owner_placeholder']}
- **Date:** {decision['date_placeholder']}
- **Evidence:** {decision['evidence_reference'] or 'TBD'}

---
"""
    (output_dir / "DECISION_LOG.md").write_text(add_header(decisions))

    # 11. AGENT_HANDOFF.md
    handoff = f"""# Agent Handoff

## Objective
{analysis.input.objective}

## Context
{analysis.input.context}

## Project Domain
{analysis.metadata.domain} {"(detected)" if analysis.metadata.detected_domain else ""}

## Constraints
- {chr(10).join("- " + c for c in analysis.input.constraints.split(chr(10)) if c.strip())}

## Key Assumptions
{chr(10).join(f"- {a['assumption']}" for a in analysis.assumptions[:3])}

## Top Risks
{chr(10).join(f"- {r['risk']}" for r in analysis.risks[:3])}

## Acceptance Criteria
{chr(10).join(f"- {c['criterion']}" for c in analysis.acceptance_criteria)}

## Control Points (Human Review Gates)
- Project charter review and approval
- Risk register review and mitigation agreement
- Acceptance criteria sign-off before execution
- Critical control plan checkpoints

## Definition of Done
- All acceptance criteria verified
- Risk mitigation plans in place
- Stakeholder sign-off obtained
- Control plan operational

## Rollback Notes
In case execution needs to be reversed:
1. Document what was changed
2. Restore previous state
3. Notify all stakeholders
4. Conduct post-mortem on failure cause

## Next Steps
1. Review this handoff document
2. Confirm understanding with team
3. Establish human review schedule
4. Proceed with execution under control plan
"""
    (output_dir / "AGENT_HANDOFF.md").write_text(add_header(handoff))

    # 12. README_OUTPUT_INDEX.md
    readme = f"""# {analysis.metadata.name} - Analysis Output Index

**Generated by ForgeMind**
This output is a readiness aid, not a certification or compliance guarantee.

## Project Summary
- **Name:** {analysis.metadata.name}
- **Domain:** {analysis.metadata.domain}
- **Maturity:** {analysis.maturity_estimate}

## Documents in This Analysis

1. **PROJECT_CHARTER.md** - High-level project definition, objectives, constraints, and success criteria

2. **RDMAICSI_MATRIX.md** - Eight-phase continuous improvement framework with questions and evidence requirements

3. **SENGE_LENS.md** - Five disciplines of learning organizations; diagnostic questions for each

4. **LEAN_WASTE_SCAN.md** - Identification of flow inefficiencies and waste categories in your project

5. **RISK_REGISTER.md** - Identified risks with cause, impact, probability, and mitigation strategies

6. **ASSUMPTION_LOG.md** - Key assumptions with validation status and risk if false

7. **ACCEPTANCE_CRITERIA.md** - Specific, testable criteria for project success

8. **BACKLOG.md** - Prioritized work items (P0-P3) for project execution

9. **CONTROL_PLAN.md** - Control mechanisms for ensuring success and detecting drift

10. **DECISION_LOG.md** - Key decisions made during planning phase

11. **AGENT_HANDOFF.md** - Agent-ready handoff document with all critical context, constraints, and gates

12. **README_OUTPUT_INDEX.md** - This file

## How to Use These Documents

1. **Start with PROJECT_CHARTER.md** to ground the team
2. **Review RISK_REGISTER.md** and **ASSUMPTION_LOG.md** to understand vulnerabilities
3. **Confirm ACCEPTANCE_CRITERIA.md** with stakeholders before proceeding
4. **Use BACKLOG.md** to prioritize work
5. **Establish CONTROL_PLAN.md** before execution starts
6. **Share AGENT_HANDOFF.md** with agents or implementers

## Readiness Assessment

- **Objective Clarity:** {'✓' if analysis.input.objective != 'Not evidenced in available input.' else '⚠'}
- **Risk Identification:** {'✓' if len(analysis.risks) >= 3 else '⚠'}
- **Assumption Validation:** {'⚠' if not any(a['status'] != 'unvalidated' for a in analysis.assumptions) else '✓'}
- **Control Mechanisms:** {'✓' if len(analysis.control_plan) > 0 else '⚠'}
- **Human Review Gates:** {'✓' if any(r['human_review_required'] for r in analysis.risks) else '⚠'}

## Next Actions

1. Review all documents with stakeholders
2. Validate and approve assumptions
3. Assign risk and control owners
4. Schedule human review gates
5. Proceed to execution with discipline
"""
    (output_dir / "README_OUTPUT_INDEX.md").write_text(readme)

    return output_dir
