"""Base generator class for all v1.1 output generators."""

from abc import ABC, abstractmethod

from forgemind.schemas.project import ProjectAnalysis


class BaseGenerator(ABC):
    """Abstract base class for output generators."""

    @abstractmethod
    def generate(self, analysis: ProjectAnalysis) -> dict:
        """
        Generate structured output from project analysis.

        Args:
            analysis: Complete ProjectAnalysis object

        Returns:
            Dictionary with generated data (format varies by generator)
        """
        pass

    def format_markdown(self, data: dict) -> str:
        """
        Format generated data as Markdown.

        Args:
            data: Output from generate()

        Returns:
            Markdown-formatted string
        """
        return self._format_markdown_impl(data)

    @abstractmethod
    def _format_markdown_impl(self, data: dict) -> str:
        """Implementation of Markdown formatting (generator-specific)."""
        pass

    def add_header(self, content: str) -> str:
        """Add standard ForgeMind header to output."""
        header = "Generated by ForgeMind\nThis output is a readiness aid, not a certification or compliance guarantee.\n\n"
        return header + content
