"""Generate GitHub pull request templates for agent-generated PRs."""

from forgemind.generators.base import BaseGenerator
from forgemind.schemas.project import ProjectAnalysis


class PRTemplateGenerator(BaseGenerator):
    """Generate PR acceptance templates."""

    def generate(self, analysis: ProjectAnalysis) -> dict:
        """Generate PR template data."""
        template = {
            "project": analysis.metadata.name,
            "domain": analysis.metadata.domain,
            "acceptance_criteria": analysis.acceptance_criteria,
            "key_risks": self._get_key_risks(analysis),
            "review_gates": self._get_review_gates(analysis),
        }
        return template

    def _get_key_risks(self, analysis: ProjectAnalysis) -> list[str]:
        """Extract high-severity risks for PR review."""
        high_risks = [
            r.get("risk", "Risk")
            for r in analysis.risks
            if r.get("severity") == "High"
        ]
        return high_risks[:3]

    def _get_review_gates(self, analysis: ProjectAnalysis) -> list[str]:
        """Extract review gates from control plan."""
        gates = []
        for control in analysis.control_plan:
            if "review" in control.get("control_measure", "").lower():
                gates.append(control.get("control_measure", ""))
        return gates[:5]

    def _format_markdown_impl(self, data: dict) -> str:
        """Format as GitHub-compatible PR template."""
        lines = [
            "## Description",
            "Agent-generated code for: [description]",
            "",
            "**Generated by:** ForgeMind v1.1 + Agent Name",
            "**Project:** " + data["project"],
            "**Domain:** " + data["domain"],
            "",
            "## Pre-Review Checklist",
            "- [ ] Code passes linter without edits",
            "- [ ] Unit tests added/updated (>80% coverage)",
            "- [ ] No hardcoded credentials or secrets in diff",
            "- [ ] No external API keys in code",
            "- [ ] Comments explain non-obvious logic",
            "- [ ] Changes match stated objective",
            "",
            "## Acceptance Criteria",
        ]

        for criterion in data["acceptance_criteria"]:
            lines.append(f"- [ ] {criterion.get('criterion', 'Criterion')}")

        lines.extend([
            "",
            "## Security Review",
            "- [ ] No SQL injection vulnerabilities",
            "- [ ] Input validation present",
            "- [ ] Error messages don't leak sensitive data",
        ])

        if data["key_risks"]:
            lines.extend([
                "",
                "## Key Risks to Review",
            ])
            for risk in data["key_risks"]:
                lines.append(f"- {risk}")

        lines.extend([
            "",
            "## Merge Requirements",
            "- **Code Owner Approval:** Required",
            "- **Security Team Approval:** Required for /auth, /api, /db changes",
            "- **All Tests Passing:** Required",
            "- **No Merge Conflicts:** Required",
            "",
            "## Rollback Plan",
            "If this PR causes issues, revert with:",
            "```bash",
            "git revert <PR_MERGE_COMMIT>",
            "```",
        ])

        content = "\n".join(lines)
        return self.add_header(content)


def generate_pr_template(analysis: ProjectAnalysis) -> str:
    """Convenience function to generate PR template."""
    generator = PRTemplateGenerator()
    data = generator.generate(analysis)
    return generator.format_markdown(data)
